In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [8]:
data = pd.read_excel("D:\\belajar_data_science\\OnlineFoodOrderPrediction.xlsx")

In [9]:
data = pd.read_excel("D:\\belajar_data_science\\OnlineFoodOrderPrediction.xlsx",index_col=-1)

In [10]:
data.head()

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback
Yes,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive
Yes,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive
Yes,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative
Yes,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive
Yes,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive

In [11]:
data.dtypes

Age                             int64
Gender                         object
Marital Status                 object
Occupation                     object
Monthly Income                 object
Educational Qualifications     object
Family size                     int64
latitude                      float64
longitude                     float64
Pin code                        int64
Output                         object
Feedback                       object
dtype: object

In [12]:
data.isnull().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
latitude                      0
longitude                     0
Pin code                      0
Output                        0
Feedback                      0
dtype: int64

In [13]:
data = data.rename(columns={
    "Marital Status":"Marital_Status",
    "Monthly Income":"Monthly_Income",
    "Educational Qualifications":"Educational_Qualifications",
    "Family size":"Family_size",
    "Pin_code":"Pin_code"
    })

In [14]:
data.head()

,Age,Gender,Marital_Status,Occupation,Monthly_Income,Educational_Qualifications,Family_size,latitude,longitude,Pin code,Output,Feedback
Yes,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive
Yes,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive
Yes,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative
Yes,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive
Yes,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive

In [15]:
# ubah data categorikal ke numerik
data['Gender'] = data['Gender'].map({
    "Male":0,
    "Female":1
})
data['Marital_Status'] = data['Marital_Status'].map({
    "Single":0,
    "Married":1,
    "Prefer not to say":2
})
data['Occupation'] = data['Occupation'].map({
    "Student":0,
    "Employee":1,
    "Self Employeed":2,
    "House wife":3
})
data['Monthly_Income'] = data['Monthly_Income'].map({
    "No Income":0,
    "25001 to 50000":1,
    "More than 50000":2,
    "10001 to 25000":3,
    "Below Rs.10000":4
})
data['Educational_Qualifications'] = data['Educational_Qualifications'].map({
    "Graduate":0,
    "Post Graduate":1,
    "Ph.D":2,
    "School":3,
    "Uneducated":4
})
data['Output'] = data['Output'].map({
    "Yes":0,
    "No":1,
})
data['Feedback'] = data['Feedback'].map({
    "Positive":1,
    "Negative":0,
}).fillna(0)

In [25]:
data.head(len(data))

,Age,Gender,Marital_Status,Occupation,Monthly_Income,Educational_Qualifications,Family_size,latitude,longitude,Pin code,Output,Feedback
Yes,20,1,0,0,0,1,4,12.9766,77.5993,560001,0,1.0
Yes,24,1,0,0,4,0,3,12.9770,77.5773,560009,0,1.0
Yes,22,0,0,0,4,1,3,12.9551,77.6593,560017,0,0.0
Yes,22,1,0,0,0,0,6,12.9473,77.5616,560019,0,1.0
Yes,22,0,0,0,4,1,4,12.9850,77.5533,560010,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
Yes,23,1,0,0,0,1,2,12.9766,77.5993,560001,0,1.0
Yes,23,1,0,0,0,1,4,12.9854,77.7081,560048,0,1.0
Yes,22,1,0,0,0,1,5,12.9850,77.5533,560010,0,1.0
Yes,23,0,0,0,4,1,2,12.9770,77.5773,560009,0,1.0
Yes,23,0,0,0,0,1,5,12.8988,77.5764,560078,0,1.0

In [17]:
data.isnull().sum()

Age                           0
Gender                        0
Marital_Status                0
Occupation                    0
Monthly_Income                0
Educational_Qualifications    0
Family_size                   0
latitude                      0
longitude                     0
Pin code                      0
Output                        0
Feedback                      0
dtype: int64

In [18]:
data.dtypes

Age                             int64
Gender                          int64
Marital_Status                  int64
Occupation                      int64
Monthly_Income                  int64
Educational_Qualifications      int64
Family_size                     int64
latitude                      float64
longitude                     float64
Pin code                        int64
Output                          int64
Feedback                      float64
dtype: object

In [19]:
correlation = data.corr()
correlation['Output'].sort_values(ascending=False)

Output                        1.000000
Marital_Status                0.281810
Age                           0.248052
Occupation                    0.240721
latitude                      0.159963
Monthly_Income                0.143392
Family_size                   0.043780
Gender                        0.034701
Pin code                      0.019929
longitude                    -0.045265
Educational_Qualifications   -0.066307
Feedback                     -0.592609
Name: Output, dtype: float64

In [22]:
# Membagi dataset
atribut = ["Marital_Status","Age","Occupation","latitude","Monthly_Income"]
x = np.array(data[atribut])
y = np.array(data["Output"])
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20,random_state=42)

In [23]:
# membuat model
model = DecisionTreeClassifier()
model.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [24]:
print(model.score(xtrain,ytrain))
print(model.score(xtest,ytest))

0.9870967741935484
0.8461538461538461